credentials:
  usernames:
    patient1:
      name: "Patient One"
      password: "$2b$12$hashedpassword1"
    patient2:
      name: "Patient Two"
      password: "$2b$12$hashedpassword2"

cookie:
  expiry_days: 30
  key: "auth_key"

preauthorized:
  emails: []
